// Document worker — walks the project tree, extracts top-of-file comments and
// exported symbols from JS/TS files, writes a flat API summary to
// ~/.flo/docs/<project-slug>-api.md
//
// Heuristic, not a full AST. Scans first 30 lines of each file for jsdoc-ish
// blocks + grep for `export (default )?(function|class|const|async)` lines.
// Cheap, useful as a refresh-on-schedule overview.

import { readdir, readFile, writeFile, mkdir, stat } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { homedir } from 'node:os';
import { join, basename, extname, relative } from 'node:path';

const FLO_HOME = process.env.FLO_HOME || join(homedir(), '.flo');
const DOCS_DIR = join(FLO_HOME, 'docs');

const SCANNABLE_EXT = new Set(['.js', '.mjs', '.cjs', '.ts', '.tsx', '.jsx']);

export default {
  name: 'document',
  description: 'Generate an auto-documentation summary of the project (exports + top-of-file comments)',
  async run({ projectDir }) {
    const dir = projectDir || process.cwd();
    if (!existsSync(DOCS_DIR)) await mkdir(DOCS_DIR, { recursive: true });
    const slug = basename(dir).replace(/[^a-z0-9]+/gi, '-').toLowerCase();
    const outFile = join(DOCS_DIR, `${slug}-api.md`);

    const files = [];
    await walk(dir, dir, 4, files);
    if (!files.length) {
      return { ok: true, summary: 'document: no scannable JS/TS files', filesScanned: 0 };
    }
    const sections = [];
    for (const f of files) {
      const summary = await extract(f);
      if (summary.exports.length || summary.header) {
        sections.push({ file: relative(dir, f), ...summary });
      }
    }
    const body = renderMarkdown(dir, sections);
    await writeFile(outFile, body, 'utf8');
    return {
      ok: true,
      summary: `document: ${sections.length} files documented → ${outFile}`,
      filesScanned: files.length,
      sectionsWritten: sections.length,
      outFile,
    };
  },
};

async function walk(rootDir, dir, depthRemaining, out) {
  if (depthRemaining < 0) return;
  let entries;
  try { entries = await readdir(dir, { withFileTypes: true }); } catch { return; }
  for (const ent of entries) {
    if (ent.name.startsWith('.') || ent.name === 'node_modules' || ent.name === 'dist' || ent.name === 'build') continue;
    const full = join(dir, ent.name);
    if (ent.isDirectory()) {
      await walk(rootDir, full, depthRemaining - 1, out);
    } else if (ent.isFile() && SCANNABLE_EXT.has(extname(full).toLowerCase())) {
      try {
        const st = await stat(full);
        if (st.size > 250_000) continue;
        out.push(full);
      } catch { /* ignore */ }
    }
  }
}

async function extract(file) {
  let body;
  try { body = await readFile(file, 'utf8'); } catch { return { header: '', exports: [] }; }
  const lines = body.split('\n');
  // Header: top contiguous comment block (// or /** */) up to first 30 lines
  let header = '';
  let inBlock = false;
  for (let i = 0; i < Math.min(30, lines.length); i++) {
    const line = lines[i].trim();
    if (line.startsWith('/**') || line.startsWith('/*')) { inBlock = true; header += line.replace(/^\/\**\s?/, '') + '\n'; continue; }
    if (inBlock) {
      if (line.endsWith('*/')) { header += line.replace(/\s?\*+\/\s*$/, '') + '\n'; inBlock = false; break; }
      header += line.replace(/^\*\s?/, '') + '\n';
      continue;
    }
    if (line.startsWith('//')) { header += line.replace(/^\/\/\s?/, '') + '\n'; continue; }
    if (line === '' && !header) continue;
    if (!line.startsWith('//') && !line.startsWith('/*') && header) break;
    if (!line.startsWith('//') && !line.startsWith('/*') && !header) break;
  }
  // Exports: grep for `export ...` declarations
  const exports = [];
  const re = /^export\s+(default\s+)?(async\s+)?(function|class|const|let|var)\s+([A-Za-z_$][A-Za-z0-9_$]*)/;
  for (const line of lines) {
    const m = line.match(re);
    if (m) exports.push({ kind: m[3], name: m[4], default: !!m[1] });
  }
  return { header: header.trim().slice(0, 600), exports };
}

function renderMarkdown(rootDir, sections) {
  const ts = new Date().toISOString();
  let out = `# API summary for ${basename(rootDir)}\n\n_Generated by flo \`document\` worker at ${ts}._\n\n`;
  out += `${sections.length} file(s) with documentation or exports.\n\n`;
  for (const s of sections) {
    out += `## \`${s.file}\`\n\n`;
    if (s.header) {
      out += '> ' + s.header.split('\n').filter(Boolean).join('\n> ') + '\n\n';
    }
    if (s.exports.length) {
      out += '**Exports:**\n\n';
      for (const e of s.exports) {
        out += `- \`${e.default ? 'default ' : ''}${e.kind} ${e.name}\`\n`;
      }
      out += '\n';
    }
  }
  return out;
}
