// Testgaps worker — finds source files that don't have a corresponding test file.
//
// Heuristic: for each .js/.ts file outside test dirs, check whether ANY file
// under the project's test root contains its basename. Imperfect but catches
// the common case of "wrote a new module, forgot the test".
//
// Output: ~/.flo/docs/<project>-testgaps.md + summary.

import { readdir, readFile, writeFile, mkdir, stat } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { homedir } from 'node:os';
import { join, basename, extname, relative } from 'node:path';

const FLO_HOME = process.env.FLO_HOME || join(homedir(), '.flo');
const DOCS_DIR = join(FLO_HOME, 'docs');

const SRC_EXT = new Set(['.js', '.mjs', '.cjs', '.ts', '.tsx', '.jsx']);
const TEST_HINTS = ['test', 'tests', '__tests__', 'spec'];

export default {
  name: 'testgaps',
  description: 'Find source files that lack a corresponding test file',
  async run({ projectDir }) {
    const dir = projectDir || process.cwd();
    if (!existsSync(DOCS_DIR)) await mkdir(DOCS_DIR, { recursive: true });
    const slug = basename(dir).replace(/[^a-z0-9]+/gi, '-').toLowerCase();
    const outFile = join(DOCS_DIR, `${slug}-testgaps.md`);

    const allSrc = [];
    const allTest = [];
    await collect(dir, dir, 4, allSrc, allTest);

    if (!allSrc.length) {
      return { ok: true, summary: 'testgaps: no source files found', sourceFiles: 0, testFiles: 0 };
    }

    // Build a set of test "haystacks" (basenames + content of test files)
    const testHaystack = new Set();
    for (const t of allTest) {
      testHaystack.add(basename(t, extname(t)).replace(/\.(test|spec)$/, ''));
      try {
        const body = await readFile(t, 'utf8');
        // Cheap content scan: find `import ... from '...'` or `require('...')`
        const re = /(?:from|require\()\s*['"]([^'"]+)['"]/g;
        let m;
        while ((m = re.exec(body))) {
          const imported = basename(m[1], extname(m[1]));
          if (imported) testHaystack.add(imported);
        }
      } catch { /* ignore */ }
    }

    const gaps = [];
    for (const s of allSrc) {
      const baseName = basename(s, extname(s));
      // Skip files that ARE tests or test helpers
      if (/(\.test|\.spec|\.fixture)\./i.test(s)) continue;
      // Skip generated / config / entrypoint shims
      if (/^(index|main|setup|config|types?|constants?)$/i.test(baseName)) continue;
      if (!testHaystack.has(baseName)) {
        gaps.push(relative(dir, s));
      }
    }

    const body = renderMarkdown(dir, allSrc.length, allTest.length, gaps);
    await writeFile(outFile, body, 'utf8');

    return {
      ok: true,
      summary: gaps.length
        ? `testgaps: ${gaps.length} of ${allSrc.length} src files lack tests (${Math.round(100 * (1 - gaps.length / allSrc.length))}% coverage)`
        : `testgaps: all ${allSrc.length} src files have tests`,
      sourceFiles: allSrc.length,
      testFiles: allTest.length,
      gapCount: gaps.length,
      coveragePct: Math.round(100 * (1 - gaps.length / Math.max(allSrc.length, 1))),
      outFile,
    };
  },
};

async function collect(rootDir, dir, depthRemaining, srcOut, testOut) {
  if (depthRemaining < 0) return;
  let entries;
  try { entries = await readdir(dir, { withFileTypes: true }); } catch { return; }
  const dirName = basename(dir).toLowerCase();
  const isTestTree = TEST_HINTS.includes(dirName);
  for (const ent of entries) {
    if (ent.name.startsWith('.') || ent.name === 'node_modules' || ent.name === 'dist' || ent.name === 'build') continue;
    const full = join(dir, ent.name);
    if (ent.isDirectory()) {
      await collect(rootDir, full, depthRemaining - 1, srcOut, testOut);
    } else if (ent.isFile() && SRC_EXT.has(extname(full).toLowerCase())) {
      try {
        const st = await stat(full);
        if (st.size > 500_000) continue;
        const isTestFile = isTestTree || /\.(test|spec)\./i.test(ent.name);
        if (isTestFile) testOut.push(full);
        else srcOut.push(full);
      } catch { /* ignore */ }
    }
  }
}

function renderMarkdown(rootDir, srcCount, testCount, gaps) {
  const ts = new Date().toISOString();
  const coverage = Math.round(100 * (1 - gaps.length / Math.max(srcCount, 1)));
  let out = `# Test gaps for ${basename(rootDir)}\n\n_Generated by flo \`testgaps\` worker at ${ts}._\n\n`;
  out += `- **Source files**: ${srcCount}\n- **Test files**: ${testCount}\n- **Estimated coverage**: ${coverage}%\n- **Gaps**: ${gaps.length}\n\n`;
  if (gaps.length) {
    out += '## Source files without tests\n\n';
    for (const g of gaps.slice(0, 200)) out += `- \`${g}\`\n`;
    if (gaps.length > 200) out += `\n_(${gaps.length - 200} more...)_\n`;
  } else {
    out += '_All non-trivial source files appear to have tests._\n';
  }
  out += `\n---\n\n_Heuristic: a source file is "covered" if its basename appears in any test file's name or import path. Trivial files (index/main/config/types/constants) are excluded._\n`;
  return out;
}
